baseURL: https://hamish-portfolio.netlify.app/
languageCode: en-us
title: Hamish Thomas
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: View Portfolio
    subtitle: |-
      An interactive website that gives information about me, 
      my previous experiences and projects that I have completed. 
    title: My Portfolio Website
  blog: {}
  contact:
    address:
      - city: Regent's Park, London, NW1 4SA
        country: UK
        street: London Business School
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: hthomas.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 (0)7776 230448
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Hamish Thomas's Portfolio Website
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/HamishThomas3
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/HamishThomas
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/hamish-thomas
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Explore Tile Overview
        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/hamish
      - name: Tempus
        url: blogs/tempus
      - name: Magna
        url: blogs/magna
      - name: Ipsum
        url: blogs/ipsum
      - name: Consequat
        url: blogs/ipsum
      - name: Etiam
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: Thomas
    title: Hamish
  tiles:
    enable: yes
    showcase:
      - image: Weald.jpeg
        subtitle: Hello World!
        title: About Me - Pre Course Assignment
        url: blogs/hamish
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Explore
    enable: yes
    subtitle: "Click EXPLORE below to view a brief summary of the different    
      components of this portfolio website. \n"
    title: Portfolio Overview
    url: blogs
