baseURL: https://hamish-portfolio.netlify.app/
languageCode: en-us
title: Hamish Thomas
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: View Portfolio
    subtitle: |-
      An interactive website that gives information about me, 
      my previous experiences and projects that I have completed. 
      It also includes a portfolio of worked examples and projects 
      that I have completed in theAM01 - Applied Statistics Module. 
      Explore my portfolio using the tiles below: 
    title: My Portfolio Website
  blog: {}
  contact:
    address:
      - city: Regent's Park, London, NW1 4SA
        country: UK
        street: London Business School
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: hthomas.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 (0)7776 230448
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Hamish Thomas's Portfolio Website
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/HamishThomas3
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/HamishThomas
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/hamish-thomas
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Explore Tile Overview
        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/hamish
      - name: Profile
        url: blogs/tempus
      - name: Gapminder & Brexit Analysis
        url: blogs/magna
      - name: Group 2 - Final Project
        url: blogs/ipsum
      - name: The General Social Survey
        url: blogs/gss
      - name: Biden's Approval Margins
        url: blogs/joeb
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: Thomas
    title: Hamish
  tiles:
    enable: yes
    showcase:
      - image: ME.jpg
        subtitle: A Short Autobiography
        title: About Me
        url: blogs/hamish
      - image: Imperial.jpg
        subtitle: Including Curriculum Vitae
        title: Profile
        url: blogs/tempus
      - image: earth.jpg
        subtitle: AM01 - Pre-Programme Assignment
        title: Gapminder & Brexit Data Analysis
        url: blogs/magna
      - image: SO2.jpg
        subtitle: AM01 - Final Project
        title: Group 2 - Ask a Manager Survey
        url: blogs/ipsum
      - image: Twitter.jpg
        subtitle: AM01 - Worked Example 1
        title: The General Social Survey
        url: blogs/gss
      - image: swab.jpg
        subtitle: AM01 - Worked Example 2
        title: Joe Biden's Approval Margins
        url: blogs/joeb
  two:
    buttonText: Explore
    enable: yes
    subtitle: "Click EXPLORE below to view a brief summary of the different    
      components of this portfolio website. \n"
    title: Portfolio Overview
    url: blogs
